kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

# Parchment parameter mappings
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.248
neo_version_range=[21.1.248,)
loader_version_range=[5.3,)
mapping_channel=official
mapping_version=1.21


## Mod Properties

mod_id=archaeologyultimine
mod_name=Archaeology Ultimine
mod_license=GNU GPLv3
mod_version=1.0.0
mod_group_id=io.github.mofish.archaeologyultimine
mod_authors=MoFish
mod_description=An FTB Ultimine addon that lets brushes excavate multiple suspicious blocks at once

